name: Test Manual Workflow

on:
    workflow_dispatch:
      inputs:
        Environment:
          description: 'The Environment i need to deploy on'
          required: true
          default: '/dev'

jobs:
    manual-job:
        runs-on: ubuntu-latest

        steps:
            - name: Exemple
              run: echo "Mon exemple"